#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
mkdir -p /pg/tmp/install/update
rm -rf /pg/tmp/install/update/*
git clone -b v1 --single-branch https://github.com/plexguide/install.git /pg/tmp/install/update
fmt -w 79 /pg/tmp/install/update/versions > /pg/tmp/install/update/wrap
versions=$(cat /pg/tmp/install/update/wrap)

# FUNCTIONS ####################################################################
common_message() {
tee <<-EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$1
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
$2
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
}

common_number() {
  read -p '↘️  Type Selection | Press [Enter]: ' typed < /dev/tty
}
common_message "🚀 PG Install Interface" "💾 Type a PG Version to Install

$versions

[Z] Exit Interface"
common_number
